### PR TITLE
Add karma users list to the website at index page

### PR DESCRIPTION
**Pull request by gsuresh86**
Fix for https://github.com/karma-runner/karma/issues/2200

### CODE REVIEW

**Comment by gsuresh86** [comment]
I signed it!

**Comment by dignifiedquire** [comment]
Thank you. There are more than those three in that issue listed though, could add the others as well please?

**Comment by gsuresh86** [comment]
Done.. added all the images

**Comment by vivganes** [comment]
LGTM

**Comment by dignifiedquire** [comment]
Thank you :octocat:

**Pull request merged**
