### PR TITLE
fix mixed content warning

### PR DESCRIPTION
**Pull request by OmgImAlexis**

### CODE REVIEW

**Comment by OmgImAlexis** [comment]
I signed it!

**Comment by Dignifiedquire** [comment]
Thanks :octocat:

**Comment by OmgImAlexis** [comment]
@Dignifiedquire does the assets directory not get rebuilt and committed on PR? Even though I changed the LESS file here the [app.css](https://github.com/karma-runner/karma-runner.github.com/blob/master/assets/css/app.css) still has the old URLs and so does the site.

**Comment by Dignifiedquire** [comment]
no I need to manually run the build and push it. will do when I'm back on my computer

**Comment by OmgImAlexis** [comment]
Alright. :+1:

**Pull request merged**
