### PR TITLE
fix broken links (mocha)

### PR DESCRIPTION
**Pull request by alfredbez**

### CODE REVIEW

**Comment by Dignifiedquire** [comment]
Thanks for your contribution @alfredbez. But isn't the official link for mocha, this: http://mochajs.org/ ?

**Comment by alfredbez** [comment]
I'll change it, see 7bd6abfc63d91953780d524674284917450eb92f

**Comment by alfredbez** [comment]
looks like there were some trailing whitespaces

**Comment by alfredbez** [comment]
#26 does only fix v0.12

**Comment by Dignifiedquire** [comment]
Already fixed thanks.

**Pull request closed without merging**
